# Generated by Django 4.2.23 on 2025-09-26 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0002_categories_alter_customusers_email_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cashdata',
            table='cash_data',
        ),
    ]
