# Generated by Django 4.2.23 on 2025-09-26 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0003_alter_cashdata_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='type_categories', to='small_web.types'),
            preserve_default=False,
        ),
    ]
