# Generated by Django 4.2.23 on 2025-09-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0004_categories_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='is_common',
        ),
    ]
