# Generated by Django 4.2.23 on 2025-09-26 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0005_remove_categories_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdata',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_cash_data', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
