# Generated by Django 4.2.23 on 2025-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0006_cashdata_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdata',
            name='sum',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Сумма'),
        ),
    ]
