# Generated by Django 4.2.23 on 2025-09-29 08:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('small_web', '0007_alter_cashdata_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdata',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2025, 9, 29, 8, 31, 10, 712370, tzinfo=datetime.timezone.utc), verbose_name='Дата создания записи'),
        ),
    ]
